<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>DebugHeroFileDungeonRPG</AssemblyName>
    <RootNamespace>DebugHeroFileDungeonRPG</RootNamespace>
    <StartupObject>DebugHeroFileDungeonRPG.Program</StartupObject>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Remove="MainForm.Input.resx" />
    <EmbeddedResource Remove="MainForm.Rendering.resx" />
    <EmbeddedResource Remove="MainForm.resx" />
    <EmbeddedResource Remove="MainForm.StageFlow.resx" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Assets\*.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="StagePlans\*.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Resources\" />
  </ItemGroup>
  <ItemGroup>
    <None Include="MainForm.Input.resx" />
    <None Include="MainForm.Rendering.resx" />
    <None Include="MainForm.resx" />
    <None Include="MainForm.StageFlow.resx" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Resources\boss\bsod_dragon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\boss\driver_k.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\boss\high_kernel.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\bsod_dragon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\driver_k.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>


